[[mgr.prepend_keymap]]
on = ["v"]
run = ["toggle", "arrow 1"]

[[mgr.prepend_keymap]]
on = ["<space>", "?"]
run = "help"

[[mgr.prepend_keymap]]
on = ["g", "?"]
run = "help"

[[help.prepend_keymap]]
on = ["/"]
run = "filter"

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "nu" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"


[[mgr.prepend_keymap]]
on = "-"
run = "leave"
desc = "Back to the parent directory"

[[mgr.prepend_keymap]]
on = "<C-h>"
run = "back"

[[mgr.prepend_keymap]]
on = "<C-l>"
run = "forward"

[[mgr.prepend_keymap]]
on = "<C-k>"
run = "plugin parent-arrow -1"

[[mgr.prepend_keymap]]
on = "<C-j>"
run = "plugin parent-arrow 1"

[[mgr.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[mgr.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "plugin duckdb -open"
desc = "open with duckdb"

[[mgr.prepend_keymap]]
on = ["g", "U"]
run = "plugin duckdb -ui"
desc = "open with duckdb ui"
