[mgr]
# Window size ratios
ratio = [2, 3, 6]

[plugin]
prepend_previewers = [
  { name = "*.csv", run = "duckdb" },
  { name = "*.tsv", run = "duckdb" },
  # { name = "*.json", run = "duckdb" },
  { name = "*.parquet", run = "duckdb" },
  { name = "*.xlsx", run = "duckdb" },
  { name = "*.db", run = "duckdb" },
  { name = "*.duckdb", run = "duckdb" },
]

# prepend_preloaders = [
#   { name = "*.csv", run = "duckdb", multi = false },
#   { name = "*.tsv", run = "duckdb", multi = false },
#   { name = "*.json", run = "duckdb", multi = false },
#   { name = "*.parquet", run = "duckdb", multi = false },
#   { name = "*.xlsx", run = "duckdb", multi = false },
# ]
